/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ordering.platform.kafka.order.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Dish extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4801585827311955671L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Dish\",\"namespace\":\"com.ordering.platform.kafka.order.avro.model\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"productList\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"logicalType\":\"uuid\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<Dish> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Dish> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Dish> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Dish> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Dish> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Dish to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Dish from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Dish instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Dish fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String name;
  private int quantity;
  private java.util.List<java.util.UUID> productList;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Dish() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param quantity The new value for quantity
   * @param productList The new value for productList
   */
  public Dish(java.lang.String name, java.lang.Integer quantity, java.util.List<java.util.UUID> productList) {
    this.name = name;
    this.quantity = quantity;
    this.productList = productList;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return quantity;
    case 2: return productList;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = value$ != null ? value$.toString() : null; break;
    case 1: quantity = (java.lang.Integer)value$; break;
    case 2: productList = (java.util.List<java.util.UUID>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public int getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(int value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'productList' field.
   * @return The value of the 'productList' field.
   */
  public java.util.List<java.util.UUID> getProductList() {
    return productList;
  }


  /**
   * Sets the value of the 'productList' field.
   * @param value the value to set.
   */
  public void setProductList(java.util.List<java.util.UUID> value) {
    this.productList = value;
  }

  /**
   * Creates a new Dish RecordBuilder.
   * @return A new Dish RecordBuilder
   */
  public static com.ordering.platform.kafka.order.avro.model.Dish.Builder newBuilder() {
    return new com.ordering.platform.kafka.order.avro.model.Dish.Builder();
  }

  /**
   * Creates a new Dish RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Dish RecordBuilder
   */
  public static com.ordering.platform.kafka.order.avro.model.Dish.Builder newBuilder(com.ordering.platform.kafka.order.avro.model.Dish.Builder other) {
    if (other == null) {
      return new com.ordering.platform.kafka.order.avro.model.Dish.Builder();
    } else {
      return new com.ordering.platform.kafka.order.avro.model.Dish.Builder(other);
    }
  }

  /**
   * Creates a new Dish RecordBuilder by copying an existing Dish instance.
   * @param other The existing instance to copy.
   * @return A new Dish RecordBuilder
   */
  public static com.ordering.platform.kafka.order.avro.model.Dish.Builder newBuilder(com.ordering.platform.kafka.order.avro.model.Dish other) {
    if (other == null) {
      return new com.ordering.platform.kafka.order.avro.model.Dish.Builder();
    } else {
      return new com.ordering.platform.kafka.order.avro.model.Dish.Builder(other);
    }
  }

  /**
   * RecordBuilder for Dish instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Dish>
    implements org.apache.avro.data.RecordBuilder<Dish> {

    private java.lang.String name;
    private int quantity;
    private java.util.List<java.util.UUID> productList;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ordering.platform.kafka.order.avro.model.Dish.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.productList)) {
        this.productList = data().deepCopy(fields()[2].schema(), other.productList);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Dish instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ordering.platform.kafka.order.avro.model.Dish other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.productList)) {
        this.productList = data().deepCopy(fields()[2].schema(), other.productList);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public int getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder setQuantity(int value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'productList' field.
      * @return The value.
      */
    public java.util.List<java.util.UUID> getProductList() {
      return productList;
    }


    /**
      * Sets the value of the 'productList' field.
      * @param value The value of 'productList'.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder setProductList(java.util.List<java.util.UUID> value) {
      validate(fields()[2], value);
      this.productList = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'productList' field has been set.
      * @return True if the 'productList' field has been set, false otherwise.
      */
    public boolean hasProductList() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'productList' field.
      * @return This builder.
      */
    public com.ordering.platform.kafka.order.avro.model.Dish.Builder clearProductList() {
      productList = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Dish build() {
      try {
        Dish record = new Dish();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Integer) defaultValue(fields()[1]);
        record.productList = fieldSetFlags()[2] ? this.productList : (java.util.List<java.util.UUID>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Dish>
    WRITER$ = (org.apache.avro.io.DatumWriter<Dish>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Dish>
    READER$ = (org.apache.avro.io.DatumReader<Dish>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










