version: '3.7'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION:-latest}
    hostname: schema-registry
#    depends_on:
#      - kafka-broker-1
#      - kafka-broker-2
#      - kafka-broker-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: '127.0.0.1:2181'
      SCHEMA_REGISTRY_LISTENERS: schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 127.0.0.1:9092
      SCHEMA_REGISTRY_DEBUG: 'true'
#    networks:
#      - ${GLOBAL_NETWORK:-kafka}
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    #    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "127.0.0.1:2181"
#    networks:
#      - ${GLOBAL_NETWORK:-kafka}